export const CHANGE_COST_OF_REAL_ESTATE_FIELD =
  "CHANGE_COST_OF_REAL_ESTATE_FIELD";
export const CHANGE_INITIAL_PAYMENT_FIELD = "CHANGE_INITIAL_PAYMENT_FIELD";
export const CHANGE_LOAN_TERM_FIELD = "CHANGE_LOAN_TERM_FIELD";
export const CHANGE_LOAN_AMOUNT_FIELD = "CHANGE_LOAN_AMOUNT_FIELD";
export const CHANGE_INTEREST_RATE_FIELD = "CHANGE_INTEREST_RATE_FIELD";
export const CHANGE_MONTHLY_PAYMENT_FIELD = "CHANGE_MONTHLY_PAYMENT_FIELD";
